//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.16 at 05:04:49 PM CEST 
//


package com.example.demosoap.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for filter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filter"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="clientId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="iban" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentDateFrom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentDateTo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentAmountFrom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentAmountTo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="transactionType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="payer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="modelDebtor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="debtorReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="modelCreditor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creditorReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="transactionStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cardTransaction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="officeTransaction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="onlinePaymentTransaction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filter", propOrder = {
    "clientId",
    "iban",
    "currency",
    "paymentDateFrom",
    "paymentDateTo",
    "paymentAmountFrom",
    "paymentAmountTo",
    "transactionType",
    "payer",
    "paymentDescription",
    "modelDebtor",
    "debtorReference",
    "modelCreditor",
    "creditorReference",
    "transactionStatus",
    "cardTransaction",
    "officeTransaction",
    "onlinePaymentTransaction"
})
public class Filter {

    @XmlElement(required = true, defaultValue = "99012460")
    protected String clientId;
    @XmlElement(required = true, defaultValue = "SI56070000000542902")
    protected String iban;
    @XmlElement(required = true, defaultValue = "EUR")
    protected String currency;
    @XmlElement(required = true, defaultValue = "2017-01-27")
    protected String paymentDateFrom;
    @XmlElement(required = true, defaultValue = "2017-02-25")
    protected String paymentDateTo;
    @XmlElement(required = true, defaultValue = "10")
    protected String paymentAmountFrom;
    @XmlElement(required = true, defaultValue = "10000")
    protected String paymentAmountTo;
    @XmlElement(required = true)
    protected String transactionType;
    @XmlElement(required = true)
    protected String payer;
    @XmlElement(required = true)
    protected String paymentDescription;
    @XmlElement(required = true)
    protected String modelDebtor;
    @XmlElement(required = true)
    protected String debtorReference;
    @XmlElement(required = true)
    protected String modelCreditor;
    @XmlElement(required = true)
    protected String creditorReference;
    @XmlElement(required = true)
    protected String transactionStatus;
    @XmlElement(required = true)
    protected String cardTransaction;
    @XmlElement(required = true)
    protected String officeTransaction;
    @XmlElement(required = true)
    protected String onlinePaymentTransaction;

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the iban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIban() {
        return iban;
    }

    /**
     * Sets the value of the iban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIban(String value) {
        this.iban = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the paymentDateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDateFrom() {
        return paymentDateFrom;
    }

    /**
     * Sets the value of the paymentDateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDateFrom(String value) {
        this.paymentDateFrom = value;
    }

    /**
     * Gets the value of the paymentDateTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDateTo() {
        return paymentDateTo;
    }

    /**
     * Sets the value of the paymentDateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDateTo(String value) {
        this.paymentDateTo = value;
    }

    /**
     * Gets the value of the paymentAmountFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAmountFrom() {
        return paymentAmountFrom;
    }

    /**
     * Sets the value of the paymentAmountFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAmountFrom(String value) {
        this.paymentAmountFrom = value;
    }

    /**
     * Gets the value of the paymentAmountTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAmountTo() {
        return paymentAmountTo;
    }

    /**
     * Sets the value of the paymentAmountTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAmountTo(String value) {
        this.paymentAmountTo = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the payer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayer() {
        return payer;
    }

    /**
     * Sets the value of the payer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayer(String value) {
        this.payer = value;
    }

    /**
     * Gets the value of the paymentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDescription() {
        return paymentDescription;
    }

    /**
     * Sets the value of the paymentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDescription(String value) {
        this.paymentDescription = value;
    }

    /**
     * Gets the value of the modelDebtor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelDebtor() {
        return modelDebtor;
    }

    /**
     * Sets the value of the modelDebtor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelDebtor(String value) {
        this.modelDebtor = value;
    }

    /**
     * Gets the value of the debtorReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtorReference() {
        return debtorReference;
    }

    /**
     * Sets the value of the debtorReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtorReference(String value) {
        this.debtorReference = value;
    }

    /**
     * Gets the value of the modelCreditor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelCreditor() {
        return modelCreditor;
    }

    /**
     * Sets the value of the modelCreditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelCreditor(String value) {
        this.modelCreditor = value;
    }

    /**
     * Gets the value of the creditorReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditorReference() {
        return creditorReference;
    }

    /**
     * Sets the value of the creditorReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditorReference(String value) {
        this.creditorReference = value;
    }

    /**
     * Gets the value of the transactionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * Sets the value of the transactionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionStatus(String value) {
        this.transactionStatus = value;
    }

    /**
     * Gets the value of the cardTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardTransaction() {
        return cardTransaction;
    }

    /**
     * Sets the value of the cardTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardTransaction(String value) {
        this.cardTransaction = value;
    }

    /**
     * Gets the value of the officeTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficeTransaction() {
        return officeTransaction;
    }

    /**
     * Sets the value of the officeTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficeTransaction(String value) {
        this.officeTransaction = value;
    }

    /**
     * Gets the value of the onlinePaymentTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnlinePaymentTransaction() {
        return onlinePaymentTransaction;
    }

    /**
     * Sets the value of the onlinePaymentTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnlinePaymentTransaction(String value) {
        this.onlinePaymentTransaction = value;
    }

}
