//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.16 at 05:04:49 PM CEST 
//


package com.example.demosoap.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demosoap.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demosoap.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetClientById }
     * 
     */
    public GetClientById createGetClientById() {
        return new GetClientById();
    }

    /**
     * Create an instance of {@link GetClientByIdResponse }
     * 
     */
    public GetClientByIdResponse createGetClientByIdResponse() {
        return new GetClientByIdResponse();
    }

    /**
     * Create an instance of {@link GetAccountsByClientId }
     * 
     */
    public GetAccountsByClientId createGetAccountsByClientId() {
        return new GetAccountsByClientId();
    }

    /**
     * Create an instance of {@link GetAccountsByClientIdResponse }
     * 
     */
    public GetAccountsByClientIdResponse createGetAccountsByClientIdResponse() {
        return new GetAccountsByClientIdResponse();
    }

    /**
     * Create an instance of {@link GetAccountTransactions }
     * 
     */
    public GetAccountTransactions createGetAccountTransactions() {
        return new GetAccountTransactions();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link GetAccountTransactionsResponse }
     * 
     */
    public GetAccountTransactionsResponse createGetAccountTransactionsResponse() {
        return new GetAccountTransactionsResponse();
    }

    /**
     * Create an instance of {@link Transactions }
     * 
     */
    public Transactions createTransactions() {
        return new Transactions();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link Clients }
     * 
     */
    public Clients createClients() {
        return new Clients();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link Accounts }
     * 
     */
    public Accounts createAccounts() {
        return new Accounts();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link BalanceTrends }
     * 
     */
    public BalanceTrends createBalanceTrends() {
        return new BalanceTrends();
    }

    /**
     * Create an instance of {@link BalanceTrend }
     * 
     */
    public BalanceTrend createBalanceTrend() {
        return new BalanceTrend();
    }

}
