//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.16 at 05:04:49 PM CEST 
//


package com.example.demosoap.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="chargeBearer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="creditorAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creditorAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creditorCity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creditorCountry" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creditorName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creditorModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="creditorReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="debtorAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="debtorAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="debtorCity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="debtorCountry" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="debtorModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="debtorName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="debtorReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="exchangeTransaction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="feeCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="flow" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentAmount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bic",
    "chargeBearer",
    "creditorAccount",
    "creditorAddress",
    "creditorCity",
    "creditorCountry",
    "creditorName",
    "creditorModel",
    "creditorReference",
    "debtorAccount",
    "debtorAddress",
    "debtorCity",
    "debtorCountry",
    "debtorModel",
    "debtorName",
    "debtorReference",
    "exchangeTransaction",
    "feeCurrency",
    "flow",
    "module",
    "paymentAmount",
    "paymentCurrency",
    "paymentDate",
    "paymentDescription",
    "priority",
    "status",
    "transactionId"
})
@XmlRootElement(name = "transactions")
public class Transactions {

    @XmlElement(required = true)
    protected String bic;
    protected String chargeBearer;
    @XmlElement(required = true)
    protected String creditorAccount;
    @XmlElement(required = true)
    protected String creditorAddress;
    @XmlElement(required = true)
    protected String creditorCity;
    @XmlElement(required = true)
    protected String creditorCountry;
    @XmlElement(required = true)
    protected String creditorName;
    protected String creditorModel;
    protected String creditorReference;
    @XmlElement(required = true)
    protected String debtorAccount;
    @XmlElement(required = true)
    protected String debtorAddress;
    @XmlElement(required = true)
    protected String debtorCity;
    @XmlElement(required = true)
    protected String debtorCountry;
    protected String debtorModel;
    @XmlElement(required = true)
    protected String debtorName;
    protected String debtorReference;
    @XmlElement(required = true)
    protected String exchangeTransaction;
    @XmlElement(required = true)
    protected String feeCurrency;
    @XmlElement(required = true)
    protected String flow;
    @XmlElement(required = true)
    protected String module;
    @XmlElement(required = true)
    protected String paymentAmount;
    @XmlElement(required = true)
    protected String paymentCurrency;
    @XmlElement(required = true)
    protected String paymentDate;
    @XmlElement(required = true)
    protected String paymentDescription;
    @XmlElement(required = true)
    protected String priority;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String transactionId;

    /**
     * Gets the value of the bic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBic() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBic(String value) {
        this.bic = value;
    }

    /**
     * Gets the value of the chargeBearer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeBearer() {
        return chargeBearer;
    }

    /**
     * Sets the value of the chargeBearer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeBearer(String value) {
        this.chargeBearer = value;
    }

    /**
     * Gets the value of the creditorAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditorAccount() {
        return creditorAccount;
    }

    /**
     * Sets the value of the creditorAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditorAccount(String value) {
        this.creditorAccount = value;
    }

    /**
     * Gets the value of the creditorAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditorAddress() {
        return creditorAddress;
    }

    /**
     * Sets the value of the creditorAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditorAddress(String value) {
        this.creditorAddress = value;
    }

    /**
     * Gets the value of the creditorCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditorCity() {
        return creditorCity;
    }

    /**
     * Sets the value of the creditorCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditorCity(String value) {
        this.creditorCity = value;
    }

    /**
     * Gets the value of the creditorCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditorCountry() {
        return creditorCountry;
    }

    /**
     * Sets the value of the creditorCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditorCountry(String value) {
        this.creditorCountry = value;
    }

    /**
     * Gets the value of the creditorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditorName() {
        return creditorName;
    }

    /**
     * Sets the value of the creditorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditorName(String value) {
        this.creditorName = value;
    }

    /**
     * Gets the value of the creditorModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditorModel() {
        return creditorModel;
    }

    /**
     * Sets the value of the creditorModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditorModel(String value) {
        this.creditorModel = value;
    }

    /**
     * Gets the value of the creditorReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditorReference() {
        return creditorReference;
    }

    /**
     * Sets the value of the creditorReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditorReference(String value) {
        this.creditorReference = value;
    }

    /**
     * Gets the value of the debtorAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtorAccount() {
        return debtorAccount;
    }

    /**
     * Sets the value of the debtorAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtorAccount(String value) {
        this.debtorAccount = value;
    }

    /**
     * Gets the value of the debtorAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtorAddress() {
        return debtorAddress;
    }

    /**
     * Sets the value of the debtorAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtorAddress(String value) {
        this.debtorAddress = value;
    }

    /**
     * Gets the value of the debtorCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtorCity() {
        return debtorCity;
    }

    /**
     * Sets the value of the debtorCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtorCity(String value) {
        this.debtorCity = value;
    }

    /**
     * Gets the value of the debtorCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtorCountry() {
        return debtorCountry;
    }

    /**
     * Sets the value of the debtorCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtorCountry(String value) {
        this.debtorCountry = value;
    }

    /**
     * Gets the value of the debtorModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtorModel() {
        return debtorModel;
    }

    /**
     * Sets the value of the debtorModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtorModel(String value) {
        this.debtorModel = value;
    }

    /**
     * Gets the value of the debtorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtorName() {
        return debtorName;
    }

    /**
     * Sets the value of the debtorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtorName(String value) {
        this.debtorName = value;
    }

    /**
     * Gets the value of the debtorReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebtorReference() {
        return debtorReference;
    }

    /**
     * Sets the value of the debtorReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebtorReference(String value) {
        this.debtorReference = value;
    }

    /**
     * Gets the value of the exchangeTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeTransaction() {
        return exchangeTransaction;
    }

    /**
     * Sets the value of the exchangeTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeTransaction(String value) {
        this.exchangeTransaction = value;
    }

    /**
     * Gets the value of the feeCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeeCurrency() {
        return feeCurrency;
    }

    /**
     * Sets the value of the feeCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeeCurrency(String value) {
        this.feeCurrency = value;
    }

    /**
     * Gets the value of the flow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlow() {
        return flow;
    }

    /**
     * Sets the value of the flow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlow(String value) {
        this.flow = value;
    }

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModule() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModule(String value) {
        this.module = value;
    }

    /**
     * Gets the value of the paymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * Sets the value of the paymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAmount(String value) {
        this.paymentAmount = value;
    }

    /**
     * Gets the value of the paymentCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentCurrency() {
        return paymentCurrency;
    }

    /**
     * Sets the value of the paymentCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentCurrency(String value) {
        this.paymentCurrency = value;
    }

    /**
     * Gets the value of the paymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDate(String value) {
        this.paymentDate = value;
    }

    /**
     * Gets the value of the paymentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDescription() {
        return paymentDescription;
    }

    /**
     * Sets the value of the paymentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDescription(String value) {
        this.paymentDescription = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

}
